/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.zonble.human.measure;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void someLibraryMethodReturnsTrue() {
//        Units classUnderTest = new Units();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
}
